build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  script:
    - git submodule update --init --recursive
    - if [ ! -d build ]; then mkdir build; fi
    - cd build
    - rm -f CMakeCache.txt
    - cmake ..
    - make
    - cd ..
  cache:
    when: on_success
    key: jeecs-build-release-$CI_COMMIT_REF_SLUG
    paths:
        - "build/*"
  tags:
    - ubuntu1804_cicd

# run tests using the binary built before
# test:
#   stage: test
#   script:
#     - ./runmytests.sh
