#pragma once

// Do not modify this file
// 'loader.hpp' will be generated by editor.

// Headers of components/systems
// E.G. #include "ExampleComponent.hpp"

namespace jemodule
{
    void register_types()
    {
        // Here to load components/system
        // e.g. jeecs::typing::type_info::of<Module::ExampleComponent>("Module::ExampleComponent");
    }
}