// THIS FILE IS AUTO GENERATED BY /script/build.wo

#define JE_IMPL
#define JE_ENABLE_DEBUG_API
#include "jeecs.hpp"

#ifdef JE_HAVE_EXTERN_LIB_WOO_API
#   error Cannot define JE_HAVE_EXTERN_LIB_WOO_API manually.
#endif

#if __has_include("jeecs_extern_library_woo_api.hpp")
#   include "jeecs_extern_library_woo_api.hpp"
#   define JE_HAVE_EXTERN_LIB_WOO_API
#endif

wo_dylib_handle_t _je_api_lib_handle = nullptr;
void je_extern_lib_woo_api_init()
{
    assert(_je_api_lib_handle == nullptr);
#ifdef JE_HAVE_EXTERN_LIB_WOO_API
    _je_api_lib_handle = je_extern_lib_woo_api_init_impl();
#endif
}

void je_extern_lib_woo_api_finish()
{
#ifdef JE_HAVE_EXTERN_LIB_WOO_API
    je_extern_lib_woo_api_finish_impl(_je_api_lib_handle);
#endif
    assert(_je_api_lib_handle != nullptr);
}
