// THIS FILE IS AUTO GENERATED BY /script/build.wo

#define JE_IMPL
#define JE_ENABLE_DEBUG_API
#include "jeecs.hpp"

#if JE4_STATIC_LINK_MODULE_AND_PKGS
extern "C"
{

}
#endif

std::vector<wo_dylib_handle_t> _je_static_module_lib_handle;
void je_extern_lib_module_init()
{
    assert(_je_static_module_lib_handle.empty());
#if JE4_STATIC_LINK_MODULE_AND_PKGS

#endif
}

void je_extern_lib_module_finish()
{
    for (auto* lib : _je_static_module_lib_handle)
    {
        assert(lib != nullptr);
        wo_unload_lib(lib, WO_DYLIB_UNREF_AND_BURY);
    }
    _je_static_module_lib_handle.clear();
}
