// THIS FILE IS AUTO GENERATED BY /script/build.wo

#define JE_IMPL
#define JE_ENABLE_DEBUG_API
#include "jeecs.hpp"

#ifdef JE_HAVE_EXTERN_LIB_3RD_PKG
#   error Cannot define JE_HAVE_EXTERN_LIB_3RD_PKG manually.
#endif

#if __has_include("jeecs_extern_library_3rd_pkg.hpp")
#   include "jeecs_extern_library_3rd_pkg.hpp"
#   define JE_HAVE_EXTERN_LIB_3RD_PKG
#endif

std::vector<wo_dylib_handle_t> _je_3rd_pkg_lib_handle;
void je_extern_lib_3rd_pkgs_init()
{
    assert(_je_3rd_pkg_lib_handle.empty()); 
#ifdef JE_HAVE_EXTERN_LIB_3RD_PKG
    je_extern_lib_3rd_pkgs_init_impl(&_je_3rd_pkg_lib_handle);
#endif
}

void je_extern_lib_3rd_pkgs_finish()
{
#ifdef JE_HAVE_EXTERN_LIB_3RD_PKG
    je_extern_lib_3rd_pkgs_finish_impl(&_je_3rd_pkg_lib_handle);
#endif
    assert(_je_3rd_pkg_lib_handle.empty());
}
